# Generated by Django 5.1 on 2025-03-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=63, verbose_name='Make')),
                ('model', models.CharField(max_length=63, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('color', models.CharField(max_length=63, verbose_name='Color')),
                ('nickname', models.CharField(max_length=63, verbose_name='Nickname')),
                ('owner', models.CharField(max_length=63, verbose_name='Owner')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Fillup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('odometer', models.IntegerField(verbose_name='Odometer')),
                ('gallons', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Gallons')),
                ('price_per_gallon', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Price per Gallon')),
                ('station', models.CharField(max_length=63, verbose_name='Station')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fillups', related_query_name='fillup', to='gas.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Fill-up',
                'verbose_name_plural': 'Fill-ups',
            },
        ),
    ]
